import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import ClientOnly from '@/components/ClientOnly';
import { ModeToggle } from '@/components/ModeToggle';
import AppProvider from '@/components/AppProvider';

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <ClientOnly>
                    <AppProvider>
                        <div className="fixed top-[50%] translate-y-[-50%] z-10">
                            <ModeToggle />
                        </div>
                        {children}
                    </AppProvider>
                </ClientOnly>
            </body>
        </html>
    );
}
